Allow selecting a target `image` in the bundle manifest
rstudio/rsconnect pull request #582
Opened 2022-05-04 17:10 UTC by dbkegley

### Approach

Updates `writeManifest` and `deployApp` with an optional `image` parameter which is used to set the `environment.image` field of the generated content manifest.

### Automated Tests

Added a new `writeManifest` testcase in `test-bundle.R` 

### QA Notes

Calls to `writeManifest(..., image = "test-image")` or `bundleApp(..., image = "test-image")` should generate a `manifest.json` in the bundle directory with an entry for `environment.image`

```
{
  "version": 1,
  "locale": "en_US",
  "platform": "4.1.2",
  "metadata": {
    "appmode": "shiny",
    "primary_rmd": null,
    "primary_html": null,
    "content_category": null,
    "has_parameters": false
  },
  "environment": {
    "image": "test-image"
  },
...
```

Omitting the `image` parameter should generate a `manifest.json` with no `environment` field.

2022-05-04 17:26 UTC, aronatkins requested changes

2022-05-04 17:26 UTC, aronatkins commented on R/bundle.R
> +    manifest$environment$image <- image
Do you need something like the following to make sure that `manifest$environment` exists?

```r
if (!is.null(image)) {
    manifest$environment <- list(image = image)
}
```

2022-05-04 18:09 UTC, aronatkins approved these changes

2022-05-04 18:27 UTC, dbkegley commented
Hm, Travis is failing but I'm not sure why. Do I need to re-generate the Rmds in `man` since I changed 2 public APIs?

2022-05-06 19:08 UTC, toph-allen approved these changes
Looks good to me. I'm guessing that the nested structure of `manifest -> environment -> image` is an existing convention from outside of `rsconnect`? I was worried that Aron's suggestion for assigning `list(image = image)` to `environment` would overwrite anything already there, but it doesn't look like there's anything else that writes to that property.

2022-05-06 19:34 UTC, dbkegley commented
`environment` is a new field in the Connect manifest that is being added so that we can select an image for a given piece of content when we are using off host execution. There's nothing else using that field today though

2022-05-16 18:49 UTC, merged